from tkinter import *
window=Tk()
window.title("calculator")
window.geometry("500x600")
window.resizable(False,False)
window.configure(background="#e30341")
window.attributes("-topmost",True)
window.attributes("-alpha",0.9)
window.iconbitmap("favicon.ico")
lbl=Label(text="enter 1st number")
lbl.place(x=50,y=30)
e1=Entry()
e1.place(x=150,y=30)
btn=Button(text="sum")
btn.place(x=200,y=50)
window.mainloop()