from tkinter import *
def add():
    sum=int(e1.get())+int(e2.get())
    e3.insert(0,str(sum))
def sub():
    sub=int(e1.get())-int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(sub))  
def mul():
    mul=int(e1.get())*int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(mul))
def div():
    div=int(e1.get())/int(e2.get())
    e3.delete(0,END)
    e3.insert(0,str(div))                      
window=Tk()
window.title("calculator")
window.geometry("500x600")
window.resizable(False,False)
window.configure(background="#e30341")
window.attributes("-topmost",True)
window.attributes("-alpha",0.9)
window.iconbitmap("favicon.ico")
lbl=Label(text="enter 1st number")
lbl.place(x=50,y=30)
lbl=Label(text="enter 2st number")
lbl.place(x=50,y=60)
e1=Entry()
e1.place(x=150,y=30)
e2=Entry()
e2.place(x=150,y=60)
btn=Button(text="sum",command=add)
btn.place(x=100,y=90)
btn1=Button(text="sub",command=sub)
btn1.place(x=150,y=90)
btn2=Button(text="mul",command=mul)
btn2.place(x=200,y=90)
btn3=Button(text="div",command=div)
btn3.place(x=250,y=90)
e3=Entry()
e3.place(x=150,y=120)
window.mainloop()